### ISSUE TITLE
System.ObjectDisposedException threw when close window and open window

### ISSUE THREAD

**Issue by jingliancui** [marcelwgn/PagerControlPolyfill#4] opened 2024-04-11 14:52 UTC
I'm using MAUI that reference the pager control, it will throw this exception in below scenario:
1. In MainPage open a new window which content include the pager, I named it as second win.
2. Close the second win
3. Open the second win
4. repeat step 2 and step 3

solution:
[SampleApp.zip](https://github.com/marcelwgn/PagerControlPolyfill/files/14978593/SampleApp.zip)

https://github.com/marcelwgn/PagerControlPolyfill/assets/16309962/0a678fb4-385b-43cd-8944-866da2989c08

![image](https://github.com/marcelwgn/PagerControlPolyfill/assets/16309962/c181a678-d6b1-46dc-af75-2150e3acb2bd)

![image](https://github.com/marcelwgn/PagerControlPolyfill/assets/16309962/cd112f4f-4ce2-49eb-87a2-1ab9c1d7bb3b)

![image](https://github.com/marcelwgn/PagerControlPolyfill/assets/16309962/58f668d2-a742-4dba-beb0-b41af2f752d7)

**Comment by jingliancui** [comment] 2024-04-13 05:01
add a maui project here to let you can reproduce the scenario
[SampleApp.zip](https://github.com/marcelwgn/PagerControlPolyfill/files/14965336/SampleApp.zip)

**Comment by marcelwgn** [comment] 2024-04-14 20:17
Thank you for reporting this issue, unfortunately I can't reproduce the issue using your repro project. Does this issue happen on a specific platform?

**Comment by jingliancui** [comment] 2024-04-15 12:00
@marcelwgn I've uploaded the video to this issue, and uploaded the solution, I will delete the previous one, please take a look. thanks.

**Comment by jingliancui** [comment] 2024-04-15 12:17
It looks like occurred by GC, so the PR I created for this issue only used try catch to wrap the code to prevent the app crash.
So I think it's better to implement IDispose to let the end user to end the control by themselves, but if you have any new idea, just ignore this one.

**Comment by marcelwgn** [comment] 2024-04-19 11:38
Version 1.0.3 should include your fix and is available now on nuget, closing hence.

**Closed as completed by marcelwgn** 2024-04-19 11:38 UTC

**Comment by jingliancui** [comment] 2024-04-20 09:18
thank you so much
